apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-demo

resources:
  - namespace.yaml
  - loggen/deployment.yaml
  - fluentbit/configmap.yaml
  - fluentbit/daemonset.yaml
  - clickhouse/configmap.yaml
  - clickhouse/statefulset.yaml
  - hyperdx/deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: otel-demo
  app.kubernetes.io/managed-by: kustomize
